### ISSUE TITLE
SkyWay-iOS-Sample compile problem

### ISSUE THREAD

**Issue by JinGuoGe** [nttcom/SkyWay-iOS-Sample#1]
Hi, ntt communication members! Thank you for your contribution. 
SkyWay-iOS-Sample is satisfied for our project requirement.
During compiling this with SkyWay framework, i failed it.
By google search, i found out that this is because of framework damaged.
I run following command: xcrun -sdk iphoneos lipo -info SkyWay
This command printed error message.
Please help me(jinguoge99@outlook.com).
Thank you.

**Comment by sho-y** [comment]
I tried to build SkyWay-iOS-Sample, but i succeeded to compile it.
Would you please try again referring to this repository's [README](https://github.com/nttcom/SkyWay-iOS-Sample/blob/master/README.md)
You can get SkyWay-iOS-SDK framework which is needed to compile SkyWay-iOS-Sample [here](https://github.com/nttcom/SkyWay-iOS-SDK/archive/v0.2.0.zip)
If you fail again, please inform more about your environment(Xcode version, iOS version,etc)

**Comment by JinGuoGe** [comment]
Thank you for your solution. I compiled it successfully. I replaced Headers,Resources, skyway with /versions/A/*.* in SkyWay.framework( Closes #1 ). 
And i have another question. I want to save remote audio and local audio to mp3 file during video chatting. Is it possible by SkyWay framework?

**Comment by sho-y** [comment]
I'm sorry for the late response.

> Thank you for your solution. I compiled it successfully. I replaced Headers,Resources, skyway with /versions/A/. in SkyWay.framework( Closes #1 ). 

I'm glad to hear that.

> And i have another question. I want to save remote audio and local audio to mp3 file during video chatting. Is it possible by SkyWay framework?

I'm sorry, but SkyWay SDK doesn't support it.
The SKWVideo class is derived from UIView, so you might be able to find a way to record through the UIView.
